### ISSUE TITLE
Can you..

### ISSUE THREAD

**Issue by laapsaap** [kulisu/metasploit-pro-trial-grabber#12]
Is it possible to use curl to get the website and echo $response using..

```
$ php -S localhost:8000
PHP 5.4.16 Development Server started at Fri May  8 22:16:08 2015
Listening on http://localhost:8000
```

to proxy to our own local browser where we can validate captcha?

**Comment by kulisu** [comment]
Hello @laapsaap,

well, i think it's NOT possible trying to proxy server's response to bypass [Google reCaptcha](https://www.google.com/recaptcha/intro/index.html).
because all the validation is on server-side instead of our browsers (client-side).

i did not survey its [new algorithm](http://stackoverflow.com/questions/27286232/how-does-new-google-recaptcha-work) before, and i believe that we will find out a solution in future :smile:
thanks again for your feedback !

Chris
